// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqL72FFR6CAVu3-4u6pUyafm-PY5Smq4o',
    appId: '1:742484032284:web:d2b643d776b1b577add8d9',
    messagingSenderId: '742484032284',
    projectId: 'trackizer-c53b6',
    authDomain: 'trackizer-c53b6.firebaseapp.com',
    storageBucket: 'trackizer-c53b6.firebasestorage.app',
    measurementId: 'G-10JF1E9R1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLw0563g4yK6idYOlNnP0n_TA1daFYmM',
    appId: '1:742484032284:android:d63a12816e1746aeadd8d9',
    messagingSenderId: '742484032284',
    projectId: 'trackizer-c53b6',
    storageBucket: 'trackizer-c53b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyPlpiI5y62jVSYs51dW2DuVLp4QwtvDY',
    appId: '1:742484032284:ios:ca1325ecde20da56add8d9',
    messagingSenderId: '742484032284',
    projectId: 'trackizer-c53b6',
    storageBucket: 'trackizer-c53b6.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyPlpiI5y62jVSYs51dW2DuVLp4QwtvDY',
    appId: '1:742484032284:ios:ca1325ecde20da56add8d9',
    messagingSenderId: '742484032284',
    projectId: 'trackizer-c53b6',
    storageBucket: 'trackizer-c53b6.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqL72FFR6CAVu3-4u6pUyafm-PY5Smq4o',
    appId: '1:742484032284:web:74975c6a1f977890add8d9',
    messagingSenderId: '742484032284',
    projectId: 'trackizer-c53b6',
    authDomain: 'trackizer-c53b6.firebaseapp.com',
    storageBucket: 'trackizer-c53b6.firebasestorage.app',
    measurementId: 'G-SB6FRXHRH7',
  );
}
